# Generated by Django 5.2.17 on 2026-09-14 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='temp-slug', max_length=250),
            preserve_default=False,
        ),
    ]
