# Generated by Django 5.2.17 on 2026-09-26 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_category_tag_alter_post_status_post_category_and_more'),
    ]

    operations = [
    ]
